- name: Arch Init Playbook
  gather_facts: no
  hosts: localhost
  become: yes
  vars:
      source_key: "ssh/id_rsa"
      dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"

  tasks:
    
    - name: 1] Check Mirror List Backup File 
      stat:
        path: /etc/pacman.d/mirrorlist.backup
      register: mirrorlist_backup
      tags:
        - mirrorlist

    - name: 1] Backup Mirror list 
      copy:
        src: /etc/pacman.d/mirrorlist
        dest: /etc/pacman.d/mirrorlist.backup
      when: not mirrorlist_backup.stat.exists
      tags:
        - mirrorlist

    - name: 1] Read the mirrorlist file
      ansible.builtin.slurp:
        src: /etc/pacman.d/mirrorlist
      register: mirrorlist
      tags:
        - mirrorlist

    - name: 1] Define required mirrorlist content
      ansible.builtin.set_fact:
        required_lines:
          - 'Server = https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch'
          - 'Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch'
          - 'Server = http://mirrors.163.com/archlinux/$repo/os/$arch'
          - 'Server = http://mirrors.aliyun.com/archlinux/$repo/os/$arch'
      tags:
        - mirrorlist

    - name: 1] Check if required lines are present
      ansible.builtin.set_fact:
        missing_lines: "{{ required_lines | difference(mirrorlist.content | b64decode | split('\n')) }}"
      tags:
        - mirrorlist

    - name: 1] Update mirrorlist if needed
      ansible.builtin.copy:
        dest: /etc/pacman.d/mirrorlist
        content: |
          {% for line in required_lines %}
          {{ line }}
          {% endfor %}
      when: missing_lines | length > 0
      tags:
        - mirrorlist
