- name: Arch Init Playbook
  gather_facts: no
  hosts: localhost
  become: yes
  vars:
      source_key: "ssh/id_rsa"
      dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"

  tasks:
    
    - name: 1] Check Mirror List Backup File 
      stat:
        path: /etc/pacman.d/mirrorlist.backup
      register: mirrorlist_backup
      tags:
        - mirrorlist

    - name: 1] Backup Mirror list 
      copy:
        src: /etc/pacman.d/mirrorlist
        dest: /etc/pacman.d/mirrorlist.backup
      when: not mirrorlist_backup.stat.exists
      tags:
        - mirrorlist

    - name: 1] Read the mirrorlist file
      ansible.builtin.slurp:
        src: /etc/pacman.d/mirrorlist
      register: mirrorlist
      tags:
        - mirrorlist

    - name: 1] Define required mirrorlist content
      ansible.builtin.set_fact:
        required_lines:
          - 'Server = https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch'
          - 'Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch'
          - 'Server = http://mirrors.163.com/archlinux/$repo/os/$arch'
          - 'Server = http://mirrors.aliyun.com/archlinux/$repo/os/$arch'
      tags:
        - mirrorlist

    - name: 1] Check if required lines are present
      ansible.builtin.set_fact:
        missing_lines: "{{ required_lines | difference(mirrorlist.content | b64decode | split('\n')) }}"
      tags:
        - mirrorlist

    - name: 1] Update mirrorlist if needed
      ansible.builtin.copy:
        dest: /etc/pacman.d/mirrorlist
        content: |
          {% for line in required_lines %}
          {{ line }}
          {% endfor %}
      when: missing_lines | length > 0
      tags:
        - mirrorlist

    - name: 2] Update pacman.conf - Color
      replace:
        path: /etc/pacman.conf
        regexp: '^#Color'
        replace: 'Color'
      tags:
        - pacman

    - name: 2] Update pacman.conf - ParallelDownload
      replace:
        path: /etc/pacman.conf
        regexp: '^#ParallelDownloads = 5'
        replace: 'ParallelDownloads = 5'
      tags:
        - pacman

    - name: 2] Update pacman.conf - VerbosePkgLists
      replace:
        path: /etc/pacman.conf
        regexp: '^#VerbosePkgLists'
        replace: 'VerbosePkgLists'
      tags:
        - pacman

    - name: 2] Update pacman.conf - ILoveCandy
      lineinfile:
        path: /etc/pacman.conf
        line: "ILoveCandy"
        insertafter: "# Misc options"
        state: present
      tags:
        - pacman

    - name: 2] Update pamcam.conf - multilib
      replace:
        path: /etc/pacman.conf
        regexp: "^#\\[multilib\\]\\n#Include = /etc/pacman.d/mirrorlist"
        replace: "[multilib]\nInclude = /etc/pacman.d/mirrorlist"
      tags:
        - pacman

    - name: 2] Pacman Update & Upgrade
      pacman:
        update_cache: yes
        upgrade: yes
      tags:
        - pacman

    - name: 3] git user.email
      git_config:
        name: user.email
        scope: global
        value: "curelesss@gmail.com"
      tags:
        - git
        - github

    - name: 3] git user.name
      git_config:
        name: user.name
        scope: global
        value: "curelesss"
      tags:
        - git
        - github

    - name: 3] Ensure .ssh directory exists
      file:
        dest: "{{ dest_key | dirname }}"
        mode: 0700
        state: directory
      tags:
        - ssh
        - github

    - name: 3] Install ssh key
      copy:
        src: "{{ source_key }}"
        dest: "{{ dest_key }}"
        mode: 0600
      tags:
        - ssh
        - github

    - name: 3] Install git config
      ansible.builtin.command:
        cmd: cp ssh/config "{{ lookup('env', 'HOME') }}/.ssh/"
      tags:
        - ssh
        - github

    - name: 3] Install openssh
      become: yes
      pacman:
        name: openssh
        state: present
      tags:
        - ssh
        - github
